version: "3.8"
services:
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    environment:
      ADMINER_PLUGINS: tables-filter dump-json edit-calendar edit-textarea sql-log
      ADMINER_DESIGN: nette
    volumes:
      - /home/mawmaw/Kerja/document/dockerfiles/adminer_plugins/index.php:/var/www/html/index.php
      - /home/mawmaw/Kerja/document/dockerfiles/adminer_plugins/server.php:/var/www/html/server.php
      - /home/mawmaw/Kerja/document/dockerfiles/adminer_plugins/oneclick-login.php:/var/www/html/plugins/oneclick-login.php
      - /home/mawmaw/Kerja/document/dockerfiles/adminer_plugins/upload.ini:/etc/php/7.4/cli/conf.d/0-upload_large_dumps.ini
      - /home/mawmaw/Kerja/document/dockerfiles/adminer_plugins/arcs-material.css:/var/www/html/designs/arcs-material/adminer.css
    ports:
      - 7070:8080

networks:
  default:
    name: db-network
    external: true
