version: '3.1'

services:
  mysql:
    image: mariadb
    container_name: wasco-mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - /home/mawmaw/Kerja/document/databases/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Megaron08
    networks:
      - db-network

  postgresdb:
    image: postgres
    container_name: postgresdb
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ma235461
    volumes:
      - /home/mawmaw/Kerja/document/databases/postgres:/var/lib/postgresql/data
    networks:
      - db-network

  mongodb:
    image : mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/mawmaw/Kerja/document/databases/mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - db-network

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    environment:
      ADMINER_PLUGINS: tables-filter dump-json
      ADMINER_DESIGN: nette
    volumes:
      # - /home/mawmaw/Kerja/document/dockerfiles/adminer_plugins/designs.php:/var/www/html/plugins-enabled/designs.php
      - /home/mawmaw/Kerja/document/dockerfiles/adminer_plugins/arcs-material.css:/var/www/html/designs/arcs-material/adminer.css
    ports:
      - 7070:8080
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
    name: db-network
