FROM php:8.0-apache
RUN apt-get update
RUN apt-get install -y libpq-dev
RUN apt-get install -y libmcrypt-dev
RUN apt-get install -y libldap2-dev
RUN apt-get install -y libxml2-dev
RUN apt-get install -y libpng-dev
RUN apt-get install -y zlib1g-dev
RUN apt-get install -y vim

RUN rm -rf /var/lib/apt/lists/*
RUN pecl install xdebug-2.8.1
RUN pecl install mcrypt-1.0.4
RUN docker-php-ext-install mysqli && \
    docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ && \
    docker-php-ext-install ldap && \
    docker-php-ext-install soap && \
    docker-php-ext-enable mcrypt && \
    docker-php-ext-enable gd && \
    docker-php-ext-enable xdebug

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN a2enmod rewrite

