FROM php:7.4-apache
RUN apt-get update -y
RUN apt-get update -y && apt-get install -y libpq-dev
RUN apt-get update -y && apt-get install -y libldap2-dev
RUN apt-get update -y && apt-get install -y libxml2-dev
RUN apt-get update -y && apt-get install -y vim
RUN apt-get update -y && apt-get install -y libmcrypt-dev
RUN apt-get update -y && apt-get install -y libpng-dev
RUN apt-get update -y && apt-get install -y zlib1g-dev

RUN rm -rf /var/lib/apt/lists/*
RUN pecl install mcrypt-1.0.3 && \
    pecl install xdebug-2.8.1
RUN docker-php-ext-install mysqli && \
    docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ && \
    docker-php-ext-install ldap && \
    docker-php-ext-install soap && \
    docker-php-ext-enable mcrypt && \
    docker-php-ext-enable gd && \
    docker-php-ext-enable xdebug
RUN a2enmod rewrite

