FROM php:5.6-apache
RUN BEFORE_PWD=$(pwd) \
    && mkdir -p /opt/xdebug \
    && cd /opt/xdebug \
    && curl -k -L https://github.com/xdebug/xdebug/archive/XDEBUG_2_5_5.tar.gz | tar zx \
    && cd xdebug-XDEBUG_2_5_5 \
    && phpize \
    && ./configure --enable-xdebug \
    && make clean \
    && sed -i 's/-O2/-O0/g' Makefile \
    && make \
    # && make test \
    && make install \
    && cd "${BEFORE_PWD}" \
    && rm -r /opt/xdebug
RUN docker-php-ext-enable xdebug
RUN apt-get update
RUN && apt-get install -y libpq-dev
RUN && apt-get install -y libldap2-dev
RUN && apt-get install -y libxml2-dev
RUN && apt-get install -y vim
RUN && apt-get install -y libmcrypt-dev
RUN && apt-get install -y libpng-dev
RUN && apt-get install -y zlib1g-dev
RUN && apt-get install -y libjpeg-dev

RUN rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-install mysql && \
    docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ && \
    docker-php-ext-install ldap && \
    docker-php-ext-install soap && \
    docker-php-ext-install mcrypt && \
    docker-php-ext-configure gd --with-jpeg-dir=/usr/lib && \
    docker-php-ext-install gd

RUN echo "xdebug.remote_enable=1" >> /usr/local/etc/php/php.ini
RUN a2enmod rewrite

