version: '2'
services:
  kanboard:
    image: kanboard/kanboard:latest
    restart: always
    ports:
      - '7071:80'
      - '443:443'
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
      - kanboard_ssl:/etc/nginx/ssl
volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl:
