version: "3.8"
services:
  kanboard:
    image: kanboard/kanboard:latest
    restart: always
    ports:
      - "7071:80"
      - "443:443"
    volumes:
      - /home/mawmaw/Kerja/document/kanboard/data:/var/www/app/data
      - /home/mawmaw/Kerja/document/kanboard/plugins:/var/www/app/plugins
      - /home/mawmaw/Kerja/document/kanboard/ssl:/etc/nginx/ssl
    environment:
      - DATABASE_HOST=wasco-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Megaron08
      - DATABASE_NAME=kanboard

networks:
  default:
    name: db-network
    external: true
