version: "3.7"

services:
  php-server5:
    container_name: php-server5
    image: php-server5:6.0
    restart: always

    build:
      context: .
      dockerfile: ./Dockerfile_php-5
    ports:
      - "8081:80"
    volumes:
      - /home/mawmaw/Kerja/apps/php/wasco:/var/www/html

  php-server7:
    container_name: php-server7
    image: php-server7:4.0
    restart: always

    build:
      context: .
      dockerfile: ./Dockerfile_php-7
    ports:
      - "8081:80"
    volumes:
      - /home/mawmaw/Kerja/apps/php/wasco:/var/www/html

networks:
  default:
    external:
      name: db-network
