version: "3.7"

services:
  php-server5:
    image: bagoesandrew/php-server:5.6
    container_name: php-server-5.6
    restart: always
    ports:
      - "8081:80"
    volumes:
      - /home/mawmaw/Kerja/apps/php/wasco:/var/www/html

  php-server7:
    image: bagoesandrew/php-server:7.4
    container_name: php-server-7.4
    restart: always
    ports:
      - "80:80"
    volumes:
      - /home/mawmaw/Kerja/apps/php/wasco:/var/www/html

networks:
  default:
   name: db-network
   external: true
