version: "3.7"

services:
  php-server7:
    container_name: php-server7
    image: php-server7:4.0
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile_php-7
    ports:
      - "80:80"
    volumes:
      - /home/mawmaw/Kerja/apps/php/wasco:/var/www/html

networks:
  default:
      name: db-network
      external: true
