version: '3.1'

services:

  db:
    image: postgres
    container_name: postgresdb
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ma235461
    volumes:
      - /home/mawmaw/Kerja/document/databases/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    environment:
      ADMINER_PLUGINS: tables-filter dump-json
      ADMINER_DESIGN: nette
    volumes:
      # - /home/mawmaw/Kerja/document/dockerfiles/adminer_plugins/designs.php:/var/www/html/plugins-enabled/designs.php
      - /home/mawmaw/Kerja/document/dockerfiles/adminer_plugins/arcs-material.css:/var/www/html/designs/arcs-material/adminer.css
    ports:
      - 7070:8080

networks:
  default:
      name: db-network
      external: true
